import { NextRequest } from "next/server";
import { chatRequestSchema } from "@/lib/schemas";

// --- Lightweight imports: no heavy deps (Anthropic, Voyage, Supabase).
// Static here so they are resolved once at module load, not on every request.
// This removes 100-300 ms of cold-start dynamic-import cost for rejected
// requests (rate-limit, validation, injection) that never need the AI stack.
import { checkRateLimit } from "@/lib/rate-limit";
import { withRouteContext } from "@/lib/request-validation";
import { getClientIp } from "@/lib/request-utils";
import { detectInjectionAttempt, sanitizeInput } from "@/lib/chat-safety";
import { GENERIC_REDIRECT_RESPONSE } from "@/lib/chat-config";
import { logger } from "@/lib/logger";
import { buildEnrichedChatMessage, buildRateLimitHeaders } from "@/lib/chat-route-utils";
import {
  CHAT_STREAM_STAGE_TIMEOUTS_MS,
  CHAT_STREAM_RESPONSE_TOTAL_CAP_MS,
  ChatStreamStageTimeoutError,
  isChatStreamStageTimeout,
  withChatStreamStageTiming,
} from "@/lib/chat-stream-timeouts";
import { encodeSseEvent } from "@/types/sse";

// PE-H5 (#808): explicit ceiling for this route, replacing Vercel's implicit
// project default. Must stay strictly greater than the worst-case internal
// budget: embedding (12s) + search (5s) + featureFlag (2s) +
// CHAT_STREAM_RESPONSE_TOTAL_CAP_MS (90s) = 109s worst case, so the internal
// timeouts below remain the binding constraint and this platform ceiling
// should never be the thing that actually fires.
//
// Vercel's currently documented default (Fluid Compute, on by default for new
// functions) is 300s across every plan tier, so 120s is a deliberately LOWER,
// explicit ceiling than that implicit default — it tightens the cost ceiling
// on a hung request rather than raising it. This assumes Fluid Compute is
// active for this project; if the dashboard (Settings > Functions > Function
// Max Duration) shows a different project-level default, confirm 120s is
// still consistent with it.
export const maxDuration = 120;

function isAbortError(error: unknown): boolean {
  return (
    (error instanceof DOMException && error.name === "AbortError") ||
    (error instanceof Error && error.name === "AbortError")
  );
}

/**
 * Streaming chat endpoint using Server-Sent Events (SSE)
 *
 * Returns a stream of text chunks as they're generated by Claude.
 * Final event includes any relevant images.
 */
export async function POST(request: NextRequest) {
  // DO-M1 (#619): bind X-Request-ID into the request context so handler logs
  // carry request_id.
  return withRouteContext(request, () => handlePost(request));
}

// BE-H1: stricter shared-bucket rate limit for requests without a trusted Vercel IP
// header. All such clients share one bucket with a tighter cap (3 req/60s) to prevent
// the "unknown" key from being used as a bypass. On Vercel production, all real
// requests carry x-vercel-forwarded-for, so this only fires in unusual conditions.
const UNTRUSTED_RATE_LIMIT = { windowMs: 60_000, maxRequests: 3, maxEntries: 1 };

async function handlePost(request: NextRequest) {
  try {
    // Rate limiting
    const ip = getClientIp(request);
    if (ip === "unknown") {
      logger.warn("[CHAT_STREAM_UNTRUSTED_IP]", {
        path: "/api/chat/stream",
        reason: "no_vercel_forwarded_for",
      });
    }
    const rateLimit = await checkRateLimit(
      ip === "unknown" ? "untrusted" : ip,
      ip === "unknown" ? UNTRUSTED_RATE_LIMIT : undefined
    );

    if (!rateLimit.allowed) {
      return new Response(
        JSON.stringify({ error: "Too many requests. Please try again later." }),
        {
          status: 429,
          headers: {
            "Content-Type": "application/json",
            ...buildRateLimitHeaders(rateLimit, true),
          },
        }
      );
    }

    // Input validation — single Zod parse path (BE-L3 #524).
    const body = await request.json().catch(() => null);
    const zodResult = chatRequestSchema.safeParse(body);
    if (!zodResult.success) {
      return new Response(
        JSON.stringify({ error: "Invalid request", details: zodResult.error.flatten() }),
        { status: 400, headers: { "Content-Type": "application/json" } }
      );
    }

    const { message, context, messageIndex } = zodResult.data;

    // Security checks
    if (message && detectInjectionAttempt(message)) {
      // Return a non-streaming response with generic redirect
      return new Response(
        JSON.stringify({
          message: GENERIC_REDIRECT_RESPONSE,
          flagged: true,
        }),
        {
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    const cleanMessage = sanitizeInput(message);

    const streamAbortController = new AbortController();
    const handleRequestAbort = () => {
      streamAbortController.abort();
    };

    if (request.signal.aborted) {
      handleRequestAbort();
    } else {
      request.signal.addEventListener("abort", handleRequestAbort, { once: true });
    }

    // --- Heavy imports: deferred until after all validation passes ---
    // VERIFIED 2026-04-23 on Next.js 16.2.4: keep these imports deferred.
    // They still avoid loading the AI stack for rejected requests, and the repo's
    // Turbopack/Anthropic regression remains documented in
    // docs/engineering/turbopack-fix.md. Do not convert back to static imports
    // without re-running that reproduction with live upstream credentials.
    const [
      { streamChatResponse, extractSourcesFromChunks },
      { generateEmbedding },
      { search },
      { isFeatureFlagEnabled },
    ] = await Promise.all([
      import("@/lib/claude"),
      import("@/lib/embeddings"),
      import("@/lib/search"),
      import("@/lib/feature-flags-server"),
    ]);

    // PE-H3: start the feature-flag lookup concurrently with embedding generation.
    // The flag is independent of the retrieval pipeline, so firing it now lets it
    // resolve (typically a fast cached Supabase read) while the embedding round-trip
    // is in flight.  We suppress unhandled rejections here; the promise is awaited
    // below once retrieval is complete.
    const asturianEnabledPromise = isFeatureFlagEnabled("asturianu_touches");
    void asturianEnabledPromise.catch(() => {});

    // Generate embedding and search — fail gracefully on upstream errors.
    // search() depends on the embedding result, so these two steps remain serial.
    // The feature-flag promise above runs in parallel with both.
    let chunks: Awaited<ReturnType<typeof search>>["chunks"] = [];
    let images: Awaited<ReturnType<typeof search>>["images"] = [];
    try {
      const queryEmbedding = await withChatStreamStageTiming(
        "embedding",
        generateEmbedding(cleanMessage)
      );
      ({ chunks, images } = await withChatStreamStageTiming(
        "search",
        search(queryEmbedding, 3, cleanMessage)
      ));
    } catch (searchErr) {
      request.signal.removeEventListener("abort", handleRequestAbort);
      logger.warn("[CHAT_STREAM_SEARCH_UNAVAILABLE]", {
        error: searchErr,
        stage: isChatStreamStageTimeout(searchErr) ? searchErr.stage : undefined,
      });
      const encoder = new TextEncoder();
      const errorStream = new ReadableStream({
        start(controller) {
          controller.enqueue(
            encoder.encode(
              encodeSseEvent({
                type: "error",
                message: "search_unavailable",
              })
            )
          );
          controller.close();
        },
      });
      return new Response(errorStream, {
        headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache" },
      });
    }

    // Enrich message with context
    const enrichedMessage = buildEnrichedChatMessage(cleanMessage, context);

    let asturianEnabled = false;
    try {
      asturianEnabled = await withChatStreamStageTiming("featureFlag", asturianEnabledPromise);
    } catch (flagErr) {
      logger.warn("[CHAT_STREAM_FEATURE_FLAG_FALLBACK]", { error: flagErr });
    }

    // Create a readable stream for SSE
    const encoder = new TextEncoder();

    // QA-M3 (#631): apply an idle timeout to the generation loop. The
    // per-stage timeouts above only cover embedding/search/feature-flag; the
    // for-await generation had no guard, so a stalled upstream stream could
    // hang the connection indefinitely. We reset an idle timer on every chunk
    // and abort the stream if no chunk arrives within the configured window.
    const IDLE_TIMEOUT_MS = CHAT_STREAM_STAGE_TIMEOUTS_MS.response;
    let idleTimer: ReturnType<typeof setTimeout> | undefined;
    let idleTimedOut = false;

    const clearIdleTimer = () => {
      if (idleTimer !== undefined) {
        clearTimeout(idleTimer);
        idleTimer = undefined;
      }
    };
    const resetIdleTimer = () => {
      clearIdleTimer();
      idleTimer = setTimeout(() => {
        idleTimedOut = true;
        streamAbortController.abort();
      }, IDLE_TIMEOUT_MS);
    };

    // PE-H5 (#808): the idle timer above resets on every chunk, so a
    // slow-but-alive trickle (a chunk arriving just under IDLE_TIMEOUT_MS,
    // forever) can keep resetting it and never trip. This second timer is
    // armed exactly once, at generation start, and is never reset by chunk
    // arrival — it bounds the TOTAL duration of the generation stage
    // regardless of chunk cadence, which is what keeps this route's internal
    // budget below the `maxDuration` declared above.
    let totalCapTimedOut = false;
    const totalCapTimer = setTimeout(() => {
      totalCapTimedOut = true;
      streamAbortController.abort();
    }, CHAT_STREAM_RESPONSE_TOTAL_CAP_MS);

    const stream = new ReadableStream({
      async start(controller) {
        try {
          // Arm the idle timer before the first chunk so a stream that never
          // yields is still bounded.
          resetIdleTimer();

          // Stream text chunks
          for await (const chunk of streamChatResponse(
            enrichedMessage,
            chunks,
            asturianEnabled,
            messageIndex,
            images,
            { signal: streamAbortController.signal }
          )) {
            if (streamAbortController.signal.aborted) {
              break;
            }

            // A chunk arrived — reset the idle window (the total cap timer
            // is untouched here by design).
            resetIdleTimer();

            // Send text chunk as SSE event
            controller.enqueue(encoder.encode(
              encodeSseEvent({ type: "text", content: chunk })
            ));
          }

          clearIdleTimer();
          clearTimeout(totalCapTimer);

          if (idleTimedOut || totalCapTimedOut) {
            throw new ChatStreamStageTimeoutError(
              "response",
              idleTimedOut ? IDLE_TIMEOUT_MS : CHAT_STREAM_RESPONSE_TOTAL_CAP_MS
            );
          }

          // Send final event with images and sources
          if (!streamAbortController.signal.aborted) {
            const sources = extractSourcesFromChunks(chunks);
            controller.enqueue(encoder.encode(
              encodeSseEvent({
                type: "done",
                images,
                sources,
              })
            ));
          }

        } catch (error) {
          if (totalCapTimedOut) {
            // Distinguished from the idle-window log below so platform kills
            // (which never log anything) and this internal hard cap are
            // both distinguishable from a normal idle-window timeout in logs.
            logger.warn("[CHAT_STREAM_RESPONSE_TOTAL_CAP]", {
              timeoutMs: CHAT_STREAM_RESPONSE_TOTAL_CAP_MS,
              reason: "total_duration_cap",
            });
            controller.enqueue(encoder.encode(
              encodeSseEvent({
                type: "error",
                message: "response_timeout",
              })
            ));
          } else if (idleTimedOut || isChatStreamStageTimeout(error)) {
            logger.warn("[CHAT_STREAM_RESPONSE_TIMEOUT]", {
              timeoutMs: IDLE_TIMEOUT_MS,
              reason: "idle_window",
            });
            controller.enqueue(encoder.encode(
              encodeSseEvent({
                type: "error",
                message: "response_timeout",
              })
            ));
          } else if (isAbortError(error) || streamAbortController.signal.aborted) {
            logger.warn("[CHAT_STREAM_ABORTED]", { reason: "client_disconnect" });
          } else {
            const err = error instanceof Error ? error : new Error(String(error));
            logger.error("[CHAT_STREAM_FAILURE]", {
              error: err.message,
              type: err.constructor?.name ?? "Error",
            });
            controller.enqueue(encoder.encode(
              encodeSseEvent({
                type: "error",
                message: "Error generating response",
              })
            ));
          }
        } finally {
          clearIdleTimer();
          clearTimeout(totalCapTimer);
          request.signal.removeEventListener("abort", handleRequestAbort);
          try {
            controller.close();
          } catch {
            // Ignore close races caused by upstream cancellation.
          }
        }
      },
      cancel() {
        clearIdleTimer();
        clearTimeout(totalCapTimer);
        streamAbortController.abort();
        request.signal.removeEventListener("abort", handleRequestAbort);
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
        ...buildRateLimitHeaders(rateLimit),
      },
    });
  } catch (error) {
    logger.error("[CHAT_STREAM_API_ERROR]", { error });
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
