import { NextRequest } from "next/server";

/**
 * Streaming chat endpoint using Server-Sent Events (SSE)
 *
 * Returns a stream of text chunks as they're generated by Claude.
 * Final event includes any relevant images.
 */
export async function POST(request: NextRequest) {
  // Dynamic imports to avoid Turbopack bundle corruption
  const { streamChatResponse, extractSourcesFromChunks } = await import(
    "@/lib/claude"
  );
  const { generateEmbedding } = await import("@/lib/embeddings");
  const { search } = await import("@/lib/search");
  const { validateChatRequest } = await import("@/lib/validation");
  const { checkRateLimit } = await import("@/lib/rate-limit");
  const { isFeatureFlagEnabled } = await import("@/lib/feature-flags-server");

  // Security modules
  const {
    detectInjectionAttempt,
    sanitizeInput,
    MAX_INPUT_LENGTH,
  } = await import("@/lib/chat-safety");
  const { GENERIC_REDIRECT_RESPONSE } = await import("@/lib/chat-config");

  const { getClientIp } = await import("@/lib/request-utils");

  try {
    // Rate limiting
    const ip = getClientIp(request);
    const rateLimit = await checkRateLimit(ip);

    if (!rateLimit.allowed) {
      return new Response(
        JSON.stringify({ error: "Too many requests. Please try again later." }),
        {
          status: 429,
          headers: {
            "Content-Type": "application/json",
            "Retry-After": String(rateLimit.retryAfter),
          },
        }
      );
    }

    // Input validation
    const body = await request.json();
    const validation = validateChatRequest(body);

    if (!validation.valid) {
      return new Response(JSON.stringify({ error: validation.error }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const { sanitizedMessage: message, sanitizedContext: context, messageIndex } = validation;

    // Security checks
    if (message && message.length > MAX_INPUT_LENGTH) {
      return new Response(
        JSON.stringify({
          error: "Message too long",
        }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    if (message && detectInjectionAttempt(message)) {
      // Return a non-streaming response with generic redirect
      return new Response(
        JSON.stringify({
          message: GENERIC_REDIRECT_RESPONSE,
          flagged: true,
        }),
        {
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    const cleanMessage = sanitizeInput(message!);

    // Generate embedding and search
    const queryEmbedding = await generateEmbedding(cleanMessage);
    const { chunks, images } = await search(queryEmbedding, 3, cleanMessage);

    // Enrich message with context
    const enrichedMessage = context
      ? `${context}\n\nPregunta del usuario: ${cleanMessage}`
      : cleanMessage;

    // Check Asturianu feature flag (cached via isFeatureFlagEnabled)
    const asturianEnabled = await isFeatureFlagEnabled("asturianu_touches");

    // Extract sources for final event
    const sources = extractSourcesFromChunks(chunks);

    // Create a readable stream for SSE
    const encoder = new TextEncoder();

    const stream = new ReadableStream({
      async start(controller) {
        try {
          // Stream text chunks
          for await (const chunk of streamChatResponse(
            enrichedMessage,
            chunks,
            asturianEnabled,
            messageIndex,
            images
          )) {
            // Send text chunk as SSE event
            const event = `data: ${JSON.stringify({ type: "text", content: chunk })}\n\n`;
            controller.enqueue(encoder.encode(event));
          }

          // Send final event with images and sources
          const finalEvent = `data: ${JSON.stringify({
            type: "done",
            images,
            sources,
          })}\n\n`;
          controller.enqueue(encoder.encode(finalEvent));

          controller.close();
        } catch (error) {
          const err = error instanceof Error ? error : new Error(String(error));
          console.error("[CHAT_STREAM_FAILURE]", {
            error: err.message,
            type: err.constructor?.name ?? "Error",
          });
          const errorEvent = `data: ${JSON.stringify({
            type: "error",
            message: "Error generating response",
          })}\n\n`;
          controller.enqueue(encoder.encode(errorEvent));
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
        "X-RateLimit-Remaining": String(rateLimit.remaining),
      },
    });
  } catch (error) {
    console.error("Stream chat API error:", error);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
