import { NextRequest } from "next/server";

// --- Lightweight imports: no heavy deps (Anthropic, Voyage, Supabase).
// Static here so they are resolved once at module load, not on every request.
// This removes 100-300 ms of cold-start dynamic-import cost for rejected
// requests (rate-limit, validation, injection) that never need the AI stack.
import { validateChatRequest } from "@/lib/validation";
import { checkRateLimit } from "@/lib/rate-limit";
import { getClientIp } from "@/lib/request-utils";
import {
  detectInjectionAttempt,
  sanitizeInput,
  MAX_INPUT_LENGTH,
} from "@/lib/chat-safety";
import { GENERIC_REDIRECT_RESPONSE } from "@/lib/chat-config";

/**
 * Streaming chat endpoint using Server-Sent Events (SSE)
 *
 * Returns a stream of text chunks as they're generated by Claude.
 * Final event includes any relevant images.
 */
export async function POST(request: NextRequest) {
  try {
    // Rate limiting
    const ip = getClientIp(request);
    const rateLimit = await checkRateLimit(ip);

    if (!rateLimit.allowed) {
      return new Response(
        JSON.stringify({ error: "Too many requests. Please try again later." }),
        {
          status: 429,
          headers: {
            "Content-Type": "application/json",
            "Retry-After": String(rateLimit.retryAfter),
          },
        }
      );
    }

    // Input validation
    const body = await request.json();
    const validation = validateChatRequest(body);

    if (!validation.valid) {
      return new Response(JSON.stringify({ error: validation.error }), {
        status: 400,
        headers: { "Content-Type": "application/json" },
      });
    }

    const { sanitizedMessage: message, sanitizedContext: context, messageIndex } = validation;

    // Security checks
    if (message && message.length > MAX_INPUT_LENGTH) {
      return new Response(
        JSON.stringify({
          error: "Message too long",
        }),
        {
          status: 400,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    if (message && detectInjectionAttempt(message)) {
      // Return a non-streaming response with generic redirect
      return new Response(
        JSON.stringify({
          message: GENERIC_REDIRECT_RESPONSE,
          flagged: true,
        }),
        {
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    const cleanMessage = sanitizeInput(message!);

    // --- Heavy imports: deferred until after all validation passes ---
    // WHY DYNAMIC: Turbopack corrupts the outbound HTTP stack for api.anthropic.com
    // when these modules (embeddings, search, supabase, claude) are statically
    // co-bundled in the same route chunk. Each module works fine on its own, but
    // the combination breaks HTTPS to Anthropic in the Turbopack build. Dynamic
    // imports isolate each module's loading context and avoid the corruption.
    // Keeping them dynamic also means rate-limited / invalid requests never pay
    // the cost of loading the AI stack.
    const { streamChatResponse, extractSourcesFromChunks } = await import(
      "@/lib/claude"
    );
    const { generateEmbedding } = await import("@/lib/embeddings");
    const { search } = await import("@/lib/search");
    const { isFeatureFlagEnabled } = await import("@/lib/feature-flags-server");

    // Generate embedding and search — fail gracefully on upstream errors
    let chunks: Awaited<ReturnType<typeof search>>["chunks"] = [];
    let images: Awaited<ReturnType<typeof search>>["images"] = [];
    try {
      const queryEmbedding = await generateEmbedding(cleanMessage);
      ({ chunks, images } = await search(queryEmbedding, 3, cleanMessage));
    } catch (searchErr) {
      console.error("[CHAT_STREAM] Embedding/search failed:", searchErr);
      const encoder = new TextEncoder();
      const errorStream = new ReadableStream({
        start(controller) {
          controller.enqueue(
            encoder.encode(
              `data: ${JSON.stringify({ type: "error", message: "search_unavailable" })}\n\n`
            )
          );
          controller.close();
        },
      });
      return new Response(errorStream, {
        headers: { "Content-Type": "text/event-stream", "Cache-Control": "no-cache" },
      });
    }

    // Enrich message with context
    const enrichedMessage = context
      ? `${context}\n\nPregunta del usuario: ${cleanMessage}`
      : cleanMessage;

    // Check Asturianu feature flag (cached via isFeatureFlagEnabled)
    const asturianEnabled = await isFeatureFlagEnabled("asturianu_touches");

    // Extract sources for final event
    const sources = extractSourcesFromChunks(chunks);

    // Create a readable stream for SSE
    const encoder = new TextEncoder();

    const stream = new ReadableStream({
      async start(controller) {
        try {
          // Stream text chunks
          for await (const chunk of streamChatResponse(
            enrichedMessage,
            chunks,
            asturianEnabled,
            messageIndex,
            images
          )) {
            // Send text chunk as SSE event
            const event = `data: ${JSON.stringify({ type: "text", content: chunk })}\n\n`;
            controller.enqueue(encoder.encode(event));
          }

          // Send final event with images and sources
          const finalEvent = `data: ${JSON.stringify({
            type: "done",
            images,
            sources,
          })}\n\n`;
          controller.enqueue(encoder.encode(finalEvent));

          controller.close();
        } catch (error) {
          const err = error instanceof Error ? error : new Error(String(error));
          console.error("[CHAT_STREAM_FAILURE]", {
            error: err.message,
            type: err.constructor?.name ?? "Error",
          });
          const errorEvent = `data: ${JSON.stringify({
            type: "error",
            message: "Error generating response",
          })}\n\n`;
          controller.enqueue(encoder.encode(errorEvent));
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        "Cache-Control": "no-cache",
        Connection: "keep-alive",
        "X-RateLimit-Remaining": String(rateLimit.remaining),
      },
    });
  } catch (error) {
    console.error("Stream chat API error:", error);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
