/**
 * ElevenLabs Agent IDs
 * Auto-generated by scripts/setup-elevenlabs-agents.ts
 * Do not edit manually.
 *
 * LOCATION-SPECIFIC: These agent IDs are specific to this Paisaxe instance.
 * When replicating, you must create new ElevenLabs voice agents and update
 * these IDs. See REPLICATION.md for instructions.
 */

/**
 * ElevenLabs API v1 base URL.
 * Shared across all routes that call the ElevenLabs API.
 */
export const ELEVENLABS_API_BASE = "https://api.elevenlabs.io/v1";

// LOCATION-SPECIFIC: Replace these agent IDs with your own ElevenLabs agents
export const ELEVENLABS_AGENT_IDS = {
  // Tourism guide for immersive stories (primary voice agent)
  pelayo: "agent_1201kgqhsdzxfkk9x7m1bjaew9mv",
  // Marketing agents for social media content
  xander: "agent_5901kg4wgebce0abca4ssyav3684",
  iris: "agent_1301kg4wggmvfwgbx91h7sn2xsbh",
  penny: "agent_1601kg4wghnzewc9aqpkf4r2fkfw",
} as const;

type ElevenLabsAgentId = keyof typeof ELEVENLABS_AGENT_IDS;

/**
 * Check if ElevenLabs agents are configured
 */
export function areAgentsConfigured(): boolean {
  return Object.values(ELEVENLABS_AGENT_IDS).some((id) => id.length > 0);
}

/**
 * Get the ElevenLabs agent ID for a given agent
 */
export function getElevenLabsAgentId(agentId: string): string | undefined {
  if (!(agentId in ELEVENLABS_AGENT_IDS)) {
    return undefined;
  }
  const id: string = ELEVENLABS_AGENT_IDS[agentId as ElevenLabsAgentId];
  return id.length > 0 ? id : undefined;
}
