#!/usr/bin/env bash
# GitHub Issue Filing Utility — Shared functions for automated agents
# Provides standardized issue creation with deduplication and labeling

set -euo pipefail

# Source agent utilities for logging (if not already sourced)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if ! declare -F log_info > /dev/null 2>&1; then
  source "$SCRIPT_DIR/agent-utils.sh"
fi

# Configuration
GITHUB_REPO="${GITHUB_REPO:-juan294/paisaxe}"
QA_LABEL="qa-failure"

# Check if GitHub CLI is available and authenticated
check_gh_cli() {
  if ! command -v gh &>/dev/null; then
    log_error "GitHub CLI (gh) is not installed. Install with: brew install gh"
    return 1
  fi

  if ! gh auth status &>/dev/null; then
    log_error "GitHub CLI is not authenticated. Run: gh auth login"
    return 1
  fi

  return 0
}

# Ensure the qa-failure label exists (creates if missing)
# Usage: ensure_qa_label
ensure_qa_label() {
  check_gh_cli || return 1

  # Check if label exists
  if ! gh label list --repo "$GITHUB_REPO" | grep -q "^$QA_LABEL"; then
    log_info "Creating '$QA_LABEL' label..."
    gh label create "$QA_LABEL" \
      --repo "$GITHUB_REPO" \
      --description "Automated QA test failure" \
      --color "d73a4a" || {
      log_warn "Label may already exist or could not be created"
    }
  fi
}

# Find an existing open issue by title prefix
# Usage: find_existing_issue "title prefix"
# Returns: Issue number if found, empty string if not
find_existing_issue() {
  local title_prefix="$1"
  check_gh_cli || return 1

  # Search for open issues with matching title and qa-failure label
  gh issue list \
    --repo "$GITHUB_REPO" \
    --label "$QA_LABEL" \
    --state open \
    --json number,title \
    --jq ".[] | select(.title | startswith(\"$title_prefix\")) | .number" \
    2>/dev/null | head -1
}

# Add a comment to an existing issue
# Usage: add_issue_comment "issue_number" "comment body"
add_issue_comment() {
  local issue_number="$1"
  local comment_body="$2"
  check_gh_cli || return 1

  gh issue comment "$issue_number" \
    --repo "$GITHUB_REPO" \
    --body "$comment_body" || {
    log_error "Failed to add comment to issue #$issue_number"
    return 1
  }

  log_success "Added comment to issue #$issue_number"
}

# Create a QA issue with deduplication
# Usage: create_qa_issue "title" "body"
# Returns: 0 on success (created or commented), 1 on failure
create_qa_issue() {
  local title="$1"
  local body="$2"
  check_gh_cli || return 1

  ensure_qa_label

  # Check for existing issue with same title prefix (first 50 chars)
  local title_prefix="${title:0:50}"
  local existing_issue
  existing_issue=$(find_existing_issue "$title_prefix")

  if [[ -n "$existing_issue" ]]; then
    log_info "Found existing issue #$existing_issue — adding comment instead of creating duplicate"
    local comment="## Recurrence on $(date '+%Y-%m-%d %H:%M')

$body"
    add_issue_comment "$existing_issue" "$comment"
    return 0
  fi

  # Create new issue
  log_info "Creating new QA issue: $title"
  gh issue create \
    --repo "$GITHUB_REPO" \
    --title "$title" \
    --body "$body" \
    --label "$QA_LABEL" || {
    log_error "Failed to create issue"
    return 1
  }

  log_success "Created QA issue: $title"
}

# Get category context description
# Usage: get_category_context "category"
get_category_context() {
  local category="$1"
  case "$category" in
    "RAG Quality")
      echo "Tests that LLM responses cite sources and use PDF content correctly."
      ;;
    "Safety & Security")
      echo "Tests for PII protection and injection resistance. **CRITICAL** - requires immediate attention."
      ;;
    "Content Boundaries")
      echo "Tests that LLM stays on topic (Asturias tourism)."
      ;;
    "Response Quality")
      echo "Tests for helpfulness, appropriate length, and language handling."
      ;;
    *)
      echo "General LLM quality test."
      ;;
  esac
}

# Create an issue for LLM test failures
# Usage: create_llm_failure_issue "category" "test_name" "details"
create_llm_failure_issue() {
  local category="$1"
  local test_name="$2"
  local details="$3"
  local category_context
  category_context=$(get_category_context "$category")

  local title="[QA] LLM Test Failure: $category - $test_name"
  local body="## LLM Quality Test Failure

**Category:** $category
**Test:** $test_name
**Date:** $(date '+%Y-%m-%d %H:%M')

### Details

\`\`\`
$details
\`\`\`

### Category Context

$category_context

### Suggested Actions

1. Review the test assertion and expected behavior
2. Check if prompt engineering changes are needed
3. Verify RAG retrieval is working correctly
4. Consider if the test expectation is reasonable

---
*Auto-generated by QA Agent*"

  create_qa_issue "$title" "$body"
}

# Create an issue for browser journey test failures
# Usage: create_journey_failure_issue "test_name" "error" "screenshot_path"
create_journey_failure_issue() {
  local test_name="$1"
  local error="$2"
  local screenshot_path="${3:-}"

  local title="[QA] Journey Test Failure: $test_name"
  local screenshot_note=""

  if [[ -n "$screenshot_path" && -f "$screenshot_path" ]]; then
    screenshot_note="
### Screenshot

A screenshot was captured at: \`$screenshot_path\`

To view, check the Playwright report or the test-results directory."
  fi

  local body="## Browser Journey Test Failure

**Test:** $test_name
**Date:** $(date '+%Y-%m-%d %H:%M')

### Error

\`\`\`
$error
\`\`\`
$screenshot_note

### Journey Test Context

Browser journey tests verify end-to-end user flows:
- Story browsing and navigation
- Chat interactions
- Favorites functionality
- Authentication flows

### Suggested Actions

1. Check if the UI has changed (selectors may need updating)
2. Verify the test server was running correctly
3. Review the Playwright trace for detailed failure info
4. Run the test locally with \`--headed\` flag for debugging:
   \`\`\`bash
   npx playwright test qa-journey.spec.ts --headed
   \`\`\`

---
*Auto-generated by QA Agent*"

  create_qa_issue "$title" "$body"
}

# Create a summary issue for multiple test failures
# Usage: create_summary_issue "pass_rate" "failed_count" "failure_summary"
create_summary_issue() {
  local pass_rate="$1"
  local failed_count="$2"
  local failure_summary="$3"

  local severity
  if [[ $pass_rate -lt 50 ]]; then
    severity="CRITICAL"
  elif [[ $pass_rate -lt 80 ]]; then
    severity="HIGH"
  else
    severity="MEDIUM"
  fi

  local title="[QA] Test Suite Failure Summary ($pass_rate% pass rate)"
  local body="## QA Test Suite Failure Summary

**Date:** $(date '+%Y-%m-%d %H:%M')
**Pass Rate:** $pass_rate%
**Failed Tests:** $failed_count
**Severity:** $severity

### Failed Tests Summary

$failure_summary

### Overall Health

$(if [[ $pass_rate -lt 50 ]]; then
  echo "🔴 **CRITICAL** - Less than 50% pass rate. Immediate attention required."
elif [[ $pass_rate -lt 80 ]]; then
  echo "🟡 **WARNING** - Pass rate below 80%. Review and fix failures."
else
  echo "🟢 **ACCEPTABLE** - Pass rate above 80%, but failures should still be addressed."
fi)

### Next Steps

1. Review individual failure issues for details
2. Prioritize safety-related failures
3. Check if failures are flaky or consistent
4. Update tests if requirements have changed

---
*Auto-generated by QA Agent*"

  create_qa_issue "$title" "$body"
}
