import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm, readFile, symlink, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
const module=()=>import('./ci-cadence-artifact.mjs');
async function fixture(run){const root=await realpath(await mkdtemp(join(tmpdir(),'b-artifact-')));const git=(...args)=>execFileSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid',...args],{cwd:root,encoding:'utf8',timeout:5000}).trim();try{git('init','--quiet','--template=');git('remote','add','origin','https://github.com/juan294/paisaxe.git');await writeFile(join(root,'.gitignore'),'.next\n');await writeFile(join(root,'package-lock.json'),'{}\n');git('add','.');git('commit','--quiet','-m','candidate');await mkdir(join(root,'.next/static/chunks'),{recursive:true});await writeFile(join(root,'.next/BUILD_ID'),'fixture-actual-file');await writeFile(join(root,'.next/static/chunks/client.js'),'window.fixture=true;');await run({root,git,sha:git('rev-parse','HEAD')});}finally{await rm(root,{recursive:true,force:true});}}
test('actual Git/files manifest binds immutable candidate, tree, build and served asset bytes',()=>fixture(async f=>{const{createCandidateManifest,verifyCandidateManifest,verifyServedArtifact}=await module();const m=await createCandidateManifest(f.root,{candidateSha:f.sha});assert.equal(m.candidateSha,f.sha);assert.equal(m.treeSha,f.git('rev-parse','HEAD^{tree}'));assert.equal(m.buildId,'fixture-actual-file');assert.equal(await verifyCandidateManifest(f.root,m),true);assert.equal(verifyServedArtifact(m,'http://127.0.0.1:3100','/_next/static/chunks/client.js',await readFile(join(f.root,'.next/static/chunks/client.js'))),true);}));
for(const fault of ['changed-build','changed-asset','wrong-head','dirty-source','symlink'])test('actual artifact '+fault+' fails identity',()=>fixture(async f=>{const{createCandidateManifest,verifyCandidateManifest}=await module();const m=await createCandidateManifest(f.root,{candidateSha:f.sha});if(fault==='changed-build')await writeFile(join(f.root,'.next/BUILD_ID'),'other');if(fault==='changed-asset')await writeFile(join(f.root,'.next/static/chunks/client.js'),'altered');if(fault==='wrong-head')m.candidateSha='a'.repeat(40);if(fault==='dirty-source')await writeFile(join(f.root,'package-lock.json'),'changed');if(fault==='symlink'){await rm(join(f.root,'.next/static/chunks/client.js'));await symlink('/etc/hosts',join(f.root,'.next/static/chunks/client.js'));}await assert.rejects(verifyCandidateManifest(f.root,m));}));
for(const origin of ['https://paisaxe.es','http://evil.invalid:3100','http://127.0.0.1:3100/path','http://u:p@127.0.0.1:3100'])test('served artifact refuses non-loopback or ambiguous origin '+origin,()=>fixture(async f=>{const{createCandidateManifest,verifyServedArtifact}=await module();const m=await createCandidateManifest(f.root,{candidateSha:f.sha});assert.throws(()=>verifyServedArtifact(m,origin,'/_next/static/chunks/client.js',Buffer.from('window.fixture=true;')));}));
