import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, rm, readFile, symlink, realpath } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const module=()=>import('./ci-cadence-artifact.mjs');
async function fixture(run){const root=await realpath(await mkdtemp(join(tmpdir(),'b-artifact-')));const git=(...args)=>execFileSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid',...args],{cwd:root,encoding:'utf8',timeout:5000}).trim();try{git('init','--quiet','--template=');git('remote','add','origin','https://github.com/juan294/paisaxe.git');await writeFile(join(root,'.gitignore'),'.next\n');await writeFile(join(root,'package-lock.json'),'{}\n');git('add','.');git('commit','--quiet','-m','candidate');await mkdir(join(root,'.next/static/chunks'),{recursive:true});await writeFile(join(root,'.next/BUILD_ID'),'fixture-actual-file');await writeFile(join(root,'.next/static/chunks/client.js'),'window.fixture=true;');await run({root,git,sha:git('rev-parse','HEAD')});}finally{await rm(root,{recursive:true,force:true});}}
test('actual Git/files manifest binds immutable candidate, tree, build and built asset bytes',()=>fixture(async f=>{const{createCandidateManifest}=await module();const m=await createCandidateManifest(f.root,{candidateSha:f.sha});assert.equal(m.candidateSha,f.sha);assert.equal(m.treeSha,f.git('rev-parse','HEAD^{tree}'));assert.equal(m.buildId,'fixture-actual-file');const bytes=await readFile(join(f.root,'.next/static/chunks/client.js'));assert.deepEqual(m.files.find(file=>file.path==='.next/static/chunks/client.js'),{path:'.next/static/chunks/client.js',bytes:bytes.length,mode:0o644,sha256:createHash('sha256').update(bytes).digest('hex')});assert.deepEqual(await createCandidateManifest(f.root,{candidateSha:f.sha}),m);}));
for(const fault of ['changed-build','changed-asset'])test('actual artifact '+fault+' changes the manifest identity',()=>fixture(async f=>{const{createCandidateManifest}=await module();const m=await createCandidateManifest(f.root,{candidateSha:f.sha});if(fault==='changed-build')await writeFile(join(f.root,'.next/BUILD_ID'),'other');else await writeFile(join(f.root,'.next/static/chunks/client.js'),'altered');assert.notEqual((await createCandidateManifest(f.root,{candidateSha:f.sha})).manifestSha256,m.manifestSha256);}));
for(const fault of ['wrong-head','dirty-source','symlink','missing-build'])test('actual artifact '+fault+' cannot produce a manifest',()=>fixture(async f=>{const{createCandidateManifest}=await module();let sha=f.sha;if(fault==='wrong-head')sha='a'.repeat(40);if(fault==='dirty-source')await writeFile(join(f.root,'package-lock.json'),'changed');if(fault==='symlink'){await rm(join(f.root,'.next/static/chunks/client.js'));await symlink('/etc/hosts',join(f.root,'.next/static/chunks/client.js'));}if(fault==='missing-build')await rm(join(f.root,'.next'),{recursive:true});await assert.rejects(createCandidateManifest(f.root,{candidateSha:sha}));}));
test('manifest CLI writes once for the checked-out candidate and fails without identity',()=>fixture(async f=>{const cli=fileURLToPath(new URL('./ci-cadence-artifact.mjs',import.meta.url));const output=join(f.root,'.next','..','manifest.json');const run=args=>spawnSync(process.execPath,[cli,...args],{cwd:f.root,encoding:'utf8',timeout:20000});await writeFile(join(f.root,'.gitignore'),'.next\nmanifest.json\n');f.git('add','.');f.git('commit','--quiet','-m','ignore');const sha=f.git('rev-parse','HEAD');const ok=run([sha,output]);assert.equal(ok.status,0,ok.stderr);assert.equal(JSON.parse(await readFile(output,'utf8')).candidateSha,sha);assert.notEqual(run([sha,output]).status,0);assert.notEqual(run([]).status,0);assert.notEqual(run(['a'.repeat(40),join(f.root,'other.json')]).status,0);}));
