#!/usr/bin/env bash
# Coverage Agent — Runs nightly at 2:00 CET via cron
# Checks test coverage, writes missing tests, updates docs/coverage-report.md
set -euo pipefail

PROJECT_DIR="/Users/juan/Documents/GenAI_Projects/paisaxe"
CLAUDE_BIN="/Users/juan/.local/bin/claude"
LOG_DIR="$PROJECT_DIR/logs"
LOG_FILE="$LOG_DIR/coverage-agent-$(date +%Y-%m-%d).log"
DOC_FILE="$PROJECT_DIR/docs/coverage-report.md"

mkdir -p "$LOG_DIR"

echo "=== Coverage Agent started at $(date) ===" | tee "$LOG_FILE"

cd "$PROJECT_DIR"

# Run the coverage agent via Claude CLI in non-interactive mode
"$CLAUDE_BIN" -p \
  --allowedTools 'Read,Write,Edit,Bash(npx vitest*),Bash(ls *),Bash(find *),Glob,Grep' \
  "You are the Paisaxe Coverage Agent. Your job is to maintain 100% test coverage.

STEPS:
1. Run: npx vitest run --coverage 2>&1
2. Parse the coverage table. Identify every file below 100% statement coverage.
3. For each file under 100%:
   a. Read the source file and its test file (if one exists).
   b. Write or update tests to cover the missing lines.
   c. Run the specific test file to confirm it passes.
4. After writing all tests, run the full suite: npx vitest run --coverage 2>&1
5. Update $DOC_FILE with a report in this exact format:

# Test Coverage Report
> Auto-generated by Coverage Agent on YYYY-MM-DD

## Summary
- **Total tests:** N
- **Test files:** N
- **Statement coverage:** N%
- **Branch coverage:** N%
- **Function coverage:** N%
- **Line coverage:** N%

## Files at 100%
(list them)

## Files below 100%
| File | Stmts | Branch | Funcs | Lines | Reason |
|------|-------|--------|-------|-------|--------|
(for each file not at 100%, explain WHY in the Reason column — e.g. 'catch block unreachable in test env', 'FormData not supported in jsdom', etc.)

## Tests Not Worth Writing
(list any tests you deliberately skipped and explain why — e.g. untestable platform code, framework internals, catch blocks that only fire in production)

## Changes Made This Run
(list test files created or modified)

RULES:
- Do NOT modify source code, only test files.
- Do NOT break existing tests.
- If a line is genuinely untestable in jsdom/vitest (e.g. cookie setAll catch blocks, FormData in Node), document it rather than forcing a brittle test.
- Commit nothing. I will review and commit manually.
- Be thorough but pragmatic." \
  >> "$LOG_FILE" 2>&1

echo "=== Coverage Agent finished at $(date) ===" | tee -a "$LOG_FILE"
