#!/usr/bin/env bash
# QA Agent — Runs weekly on Sunday at 8:00 AM via launchd (com.paisaxe.qa-agent)
# Performs automated LLM testing: RAG quality, safety, boundaries, and response quality
# Budget-conscious: samples tests and rotates categories weekly
set -euo pipefail

PROJECT_DIR="/Users/juan/Documents/GenAI_Projects/paisaxe"
LOG_DIR="$PROJECT_DIR/logs"
LOG_FILE="$LOG_DIR/qa-agent-$(date +%Y-%m-%d).log"
REPORT_FILE="$PROJECT_DIR/docs/agents/qa-report.md"

mkdir -p "$LOG_DIR"

# Source shared utilities and check feature flags
source "$PROJECT_DIR/scripts/lib/agent-utils.sh"

# Check if agent is enabled via feature flags
log_info "=== QA Agent starting ===" | tee -a "$LOG_FILE"
log_info "Checking feature flags..." | tee -a "$LOG_FILE"
if ! check_agent_enabled "qa_agent_enabled"; then
  log_info "=== QA Agent disabled by feature flag — exiting gracefully ===" | tee -a "$LOG_FILE"
  exit 0
fi
log_success "Feature flags enabled — proceeding with QA Agent" | tee -a "$LOG_FILE"

cd "$PROJECT_DIR"

# Get configuration from feature flag
TESTS_PER_CATEGORY=$(get_agent_config "qa_agent_enabled" "testsPerCategory" || echo "3")
log_info "Running $TESTS_PER_CATEGORY tests per category" | tee -a "$LOG_FILE"

# Initialize report
write_report_header "QA Testing Report" "$REPORT_FILE"

{
  echo "## Test Configuration"
  echo ""
  echo "- **Tests per category**: $TESTS_PER_CATEGORY"
  echo "- **Categories tested**: RAG Quality, Safety, Boundaries, Response Quality"
  echo ""
} >> "$REPORT_FILE"

# Run the automated test suite
log_info "Running automated QA tests..." | tee -a "$LOG_FILE"

# Export for the test runner
export QA_TESTS_PER_CATEGORY="$TESTS_PER_CATEGORY"
export QA_REPORT_FILE="$REPORT_FILE"

# Run vitest with the QA test suite
npm run test:qa 2>&1 | tee -a "$LOG_FILE" || {
  log_warn "Some QA tests failed — see report for details" | tee -a "$LOG_FILE"
}

# Add manual testing reminder
{
  echo ""
  echo "---"
  echo ""
  echo "## Manual Testing Required"
  echo ""
  echo "The following test categories require human testing (see \`docs/testbed.md\`):"
  echo ""
  echo "- Voice Agent interactions (microphone, audio, interruptions)"
  echo "- Visual UI/UX quality assessment"
  echo "- Accessibility with screen readers"
  echo "- Mobile device testing"
  echo "- OAuth/authentication flows"
  echo ""
  echo "---"
  echo ""
  echo "*Report generated by QA Agent*"
} >> "$REPORT_FILE"

log_success "QA report written to $REPORT_FILE" | tee -a "$LOG_FILE"
log_info "=== QA Agent finished ===" | tee -a "$LOG_FILE"
