#!/usr/bin/env bash
# Security Agent — Runs weekly on Monday at 9:00 AM via launchd (com.paisaxe.security-agent)
# Performs npm audit and license checks, outputs to docs/security-report.md
set -euo pipefail

PROJECT_DIR="/Users/juan/Documents/GenAI_Projects/paisaxe"
LOG_DIR="$PROJECT_DIR/logs"
LOG_FILE="$LOG_DIR/security-agent-$(date +%Y-%m-%d).log"
REPORT_FILE="$PROJECT_DIR/docs/security-report.md"

mkdir -p "$LOG_DIR"

# Source shared utilities and check feature flags
source "$PROJECT_DIR/scripts/lib/agent-utils.sh"

# Check if agent is enabled via feature flags
log_info "=== Security Agent starting ===" | tee -a "$LOG_FILE"
log_info "Checking feature flags..." | tee -a "$LOG_FILE"
if ! check_agent_enabled "security_agent_enabled"; then
  log_info "=== Security Agent disabled by feature flag — exiting gracefully ===" | tee -a "$LOG_FILE"
  exit 0
fi
log_success "Feature flags enabled — proceeding with Security Agent" | tee -a "$LOG_FILE"

cd "$PROJECT_DIR"

# Initialize report
write_report_header "Security Report" "$REPORT_FILE"

# Run npm audit
log_info "Running npm audit..." | tee -a "$LOG_FILE"

{
  echo "## Vulnerability Scan"
  echo ""
  echo "\`\`\`"
} >> "$REPORT_FILE"

npm audit --audit-level=moderate 2>&1 >> "$REPORT_FILE" || {
  log_warn "npm audit found vulnerabilities" | tee -a "$LOG_FILE"
}

{
  echo "\`\`\`"
  echo ""
} >> "$REPORT_FILE"

# Run license check
log_info "Running license check..." | tee -a "$LOG_FILE"

{
  echo "## License Summary"
  echo ""
  echo "\`\`\`"
} >> "$REPORT_FILE"

npx license-checker --production --summary 2>&1 >> "$REPORT_FILE" || {
  log_warn "license-checker encountered issues" | tee -a "$LOG_FILE"
}

{
  echo "\`\`\`"
  echo ""
} >> "$REPORT_FILE"

# Check for copyleft licenses
log_info "Checking for copyleft licenses..." | tee -a "$LOG_FILE"

{
  echo "## Copyleft License Check"
  echo ""
} >> "$REPORT_FILE"

COPYLEFT_OUTPUT=$(npx license-checker --production --failOn "GPL-2.0;GPL-3.0;AGPL-3.0;LGPL-2.0;LGPL-2.1;LGPL-3.0" 2>&1) && {
  echo "No copyleft licenses found." >> "$REPORT_FILE"
  log_success "No copyleft licenses detected" | tee -a "$LOG_FILE"
} || {
  echo "**WARNING: Copyleft licenses detected!**" >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "\`\`\`" >> "$REPORT_FILE"
  echo "$COPYLEFT_OUTPUT" >> "$REPORT_FILE"
  echo "\`\`\`" >> "$REPORT_FILE"
  log_warn "Copyleft licenses detected — review required" | tee -a "$LOG_FILE"
}

# Add outdated packages info
log_info "Checking for outdated packages..." | tee -a "$LOG_FILE"

{
  echo ""
  echo "## Outdated Packages"
  echo ""
  echo "\`\`\`"
} >> "$REPORT_FILE"

npm outdated 2>&1 >> "$REPORT_FILE" || true

{
  echo "\`\`\`"
  echo ""
} >> "$REPORT_FILE"

# Summary
{
  echo "---"
  echo ""
  echo "*Report generated by Security Agent*"
} >> "$REPORT_FILE"

log_success "Security report written to $REPORT_FILE" | tee -a "$LOG_FILE"
log_info "=== Security Agent finished ===" | tee -a "$LOG_FILE"
